name: PR Verify

on:
  workflow_dispatch: 
  pull_request:
    branches: [ "main" ]  

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Log into container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Build
        uses: ./.github/templates/build-nuke
        with:
          stepName: "Build"
          target: "Compile"
